name: Commit
on: [push]

env:
  CI_NAME: Commit CI
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-13
          - windows-2022
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: vars
        shell: bash
        run: |
          echo ${GITHUB_REF#refs/*/}
          echo CI_BRANCH=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

      - name: Install macOS utils
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install coreutils clang-format

      - name: Calculate JNI cache hash
        id: cache-hash
        shell: bash
        run: script/cache-hash.sh

      - name: Fetch JNI cache
        uses: actions/cache@v3
        id: jni-cache
        with:
          path: "app/prebuilt"
          key: ${{ matrix.os }}-trime-jni-debug-${{ steps.cache-hash.outputs.hash }}

      - name: Fetch submodules
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: |
          git submodule update --init --recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Check code style
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          make style-lint

      # `make debug` works not well on Windows
      - name: Build debug Trime
        run: |
          ./gradlew :app:assembleDebug

      - name: Add JNI cache
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        shell: bash
        run: cp -R app/build/intermediates/stripped_native_libs/debug/out/lib app/prebuilt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: trime-${{ matrix.os }}
          path: app/build/outputs/apk/debug/
          # keep 90 days
          retention-days: 90

      - name: Upload APK artifact (ARM64_V8A only)
        uses: actions/upload-artifact@v3
        with:
          name: trime-arm64-v8a-${{ matrix.os }}
          path: app/build/outputs/apk/debug/*arm64-v8a-*.apk
          # keep 90 days
          retention-days: 90

      - name: Upload JNI artifact (librime_jni.so)
        uses: actions/upload-artifact@v3
        with:
          name: librime_jni
          path: app/build/intermediates/stripped_native_libs/debug/out/lib/*
          # keep 90 days
          retention-days: 90
