name: release ci
on:
  push:
    tags:
      - '*'
env:
  CI_NAME: Release CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: vars
        run: |
          echo ${GITHUB_REF#refs/*/}
          echo CI_BRANCH=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

      - name: Calculate JNI cache hash
        id: cache-hash
        run: script/cache-hash.sh

      - name: Fetch JNI cache
        uses: actions/cache@v3
        id: jni-cache
        with:
          path: "app/prebuilt"
          key: ${{ runner.os }}-trime-jni-debug-${{ steps.cache-hash.outputs.hash }}

      - name: Fetch submodules
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: |
          git submodule update --init --recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup keystore
        run: |
          echo "set up keystore for release"
          echo "need help!!"

      - name: Install dependency
        run: ./script/dependency.sh

      - name: Build Trime
        run: make debug

      - name: Add JNI cache
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        # TODO: replace debug with release after we switched to "make release"
        run: cp -R app/build/intermediates/stripped_native_libs/debug/out/lib app/prebuilt

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          commitMode: true
          configurationJson: |
            {
              "template": "Change log from #{{FROM_TAG}} to #{{TO_TAG}}: #{{RELEASE_DIFF}}\n#{{UNCATEGORIZED}}",
              "pr_template": "- [#{{MERGE_SHA}}] - #{{TITLE}}"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/**/*.apk"
          body: |
            ${{ steps.build_changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
